"""initial multi user schema

Revision ID: e26c5288e11f
Revises:
Create Date: 2026-08-02 17:34:14.662811
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e26c5288e11f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # The previous local-only release did not use Alembic and its organizer
    # rows have no owner. Silently adopting those rows would violate tenant
    # isolation, while creating these tables over them produces a cryptic SQL
    # error. Refuse the unsafe in-place upgrade with an actionable message.
    existing_tables = set(sa.inspect(op.get_bind()).get_table_names())
    legacy_tables = {"categories", "messages", "tags", "message_tags"}
    if existing_tables.intersection(legacy_tables):
        raise RuntimeError(
            "Unsupported legacy single-user database detected. Export any data "
            "you need and run this multi-user release against a fresh database."
        )
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('normalized_email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=512), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('failed_login_attempts >= 0', name=op.f('ck_users_failed_login_attempts_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('normalized_email', name=op.f('uq_users_normalized_email'))
    )
    op.create_table('categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('normalized_name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('system_key', sa.String(length=50), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_categories_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    sa.UniqueConstraint('user_id', 'id', name='uq_categories_user_id_id'),
    sa.UniqueConstraint('user_id', 'normalized_name', name='uq_categories_user_id_normalized_name'),
    sa.UniqueConstraint('user_id', 'slug', name='uq_categories_user_id_slug'),
    sa.UniqueConstraint('user_id', 'system_key', name='uq_categories_user_id_system_key')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index('ix_categories_user_id_position_id', ['user_id', 'position', 'id'], unique=False)

    op.create_table('scan_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('state', sa.String(length=24), nullable=False),
    sa.Column('stop_requested', sa.Boolean(), nullable=False),
    sa.Column('messages_scanned', sa.Integer(), nullable=False),
    sa.Column('pages_scanned', sa.Integer(), nullable=False),
    sa.Column('page_size', sa.Integer(), nullable=False),
    sa.Column('last_message_id', sa.BigInteger(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("state IN ('pending', 'running', 'stopping', 'completed', 'failed', 'cancelled')", name=op.f('ck_scan_jobs_valid_state')),
    sa.CheckConstraint('messages_scanned >= 0', name=op.f('ck_scan_jobs_messages_scanned_non_negative')),
    sa.CheckConstraint('page_size > 0', name=op.f('ck_scan_jobs_page_size_positive')),
    sa.CheckConstraint('pages_scanned >= 0', name=op.f('ck_scan_jobs_pages_scanned_non_negative')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_scan_jobs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scan_jobs'))
    )
    with op.batch_alter_table('scan_jobs', schema=None) as batch_op:
        batch_op.create_index('ix_scan_jobs_state_created_at', ['state', 'created_at'], unique=False)
        batch_op.create_index('ix_scan_jobs_user_id_created_at', ['user_id', 'created_at'], unique=False)
        batch_op.create_index('uq_scan_jobs_user_id_active', ['user_id'], unique=True, postgresql_where=sa.text("state IN ('pending', 'running', 'stopping')"), sqlite_where=sa.text("state IN ('pending', 'running', 'stopping')"))

    op.create_table('tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('normalized_name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_tags_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags')),
    sa.UniqueConstraint('user_id', 'id', name='uq_tags_user_id_id'),
    sa.UniqueConstraint('user_id', 'normalized_name', name='uq_tags_user_id_normalized_name')
    )
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.create_index('ix_tags_user_id_normalized_name', ['user_id', 'normalized_name'], unique=False)

    op.create_table('telegram_connections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=True),
    sa.Column('phone_encrypted', sa.Text(), nullable=True),
    sa.Column('session_encrypted', sa.Text(), nullable=True),
    sa.Column('state', sa.String(length=24), nullable=False),
    sa.Column('pending_phone_code_hash_encrypted', sa.Text(), nullable=True),
    sa.Column('pending_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_required', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("state IN ('disconnected', 'pending', 'connected', 'error')", name=op.f('ck_telegram_connections_valid_state')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_telegram_connections_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_telegram_connections')),
    sa.UniqueConstraint('telegram_user_id', name=op.f('uq_telegram_connections_telegram_user_id')),
    sa.UniqueConstraint('user_id', 'id', name='uq_telegram_connections_user_id_id'),
    sa.UniqueConstraint('user_id', name=op.f('uq_telegram_connections_user_id'))
    )
    op.create_table('web_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('csrf_token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('rotated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('idle_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_web_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_web_sessions')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_web_sessions_token_hash'))
    )
    with op.batch_alter_table('web_sessions', schema=None) as batch_op:
        batch_op.create_index('ix_web_sessions_expires_at', ['expires_at'], unique=False)
        batch_op.create_index('ix_web_sessions_user_id_revoked_at', ['user_id', 'revoked_at'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('media_type', sa.String(length=50), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.Column('sender_name', sa.String(length=255), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id', 'category_id'], ['categories.user_id', 'categories.id'], name='fk_messages_user_id_category_id_categories', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_messages_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages')),
    sa.UniqueConstraint('user_id', 'id', name='uq_messages_user_id_id'),
    sa.UniqueConstraint('user_id', 'telegram_id', name='uq_messages_user_id_telegram_id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index('ix_messages_user_id_category_id_date', ['user_id', 'category_id', 'date'], unique=False)
        batch_op.create_index('ix_messages_user_id_date_id', ['user_id', 'date', 'id'], unique=False)

    op.create_table('message_tags',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id', 'message_id'], ['messages.user_id', 'messages.id'], name='fk_message_tags_user_id_message_id_messages', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id', 'tag_id'], ['tags.user_id', 'tags.id'], name='fk_message_tags_user_id_tag_id_tags', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'message_id', 'tag_id', name=op.f('pk_message_tags'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message_tags')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index('ix_messages_user_id_date_id')
        batch_op.drop_index('ix_messages_user_id_category_id_date')

    op.drop_table('messages')
    with op.batch_alter_table('web_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_web_sessions_user_id_revoked_at')
        batch_op.drop_index('ix_web_sessions_expires_at')

    op.drop_table('web_sessions')
    op.drop_table('telegram_connections')
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_index('ix_tags_user_id_normalized_name')

    op.drop_table('tags')
    with op.batch_alter_table('scan_jobs', schema=None) as batch_op:
        batch_op.drop_index('uq_scan_jobs_user_id_active', postgresql_where=sa.text("state IN ('pending', 'running', 'stopping')"), sqlite_where=sa.text("state IN ('pending', 'running', 'stopping')"))
        batch_op.drop_index('ix_scan_jobs_user_id_created_at')
        batch_op.drop_index('ix_scan_jobs_state_created_at')

    op.drop_table('scan_jobs')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index('ix_categories_user_id_position_id')

    op.drop_table('categories')
    op.drop_table('users')
    # ### end Alembic commands ###
